@page "/student/viewsubmission"
@inject HttpClient Http
@inject NavigationManager Navigation
@inject AuthenticationStateProvider _authenticationStateProvider
@attribute [Authorize(Roles = "Administrators, Students")]

<h4>View your tests</h4>

<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Exam Name</th>
                <th>Exam Code</th>
                <th>Question Total</th>
                <th>Date Submitted</th>
                <th>Mark</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                @foreach (var StudentExam in StudentExams)
            {
                @foreach (var ex in Exams) {
                        if (ex.ExamId == StudentExam.ExamId) {
                <td>@ex.ExamName</td>
                <td>@ex.ExamCode</td>
                <td>@ex.QuestionAmount</td>
                        }
                    }
                <td>@StudentExam.Date.ToShortDateString()</td>
                @if (StudentExam.Status == true)
                {
                <td>@StudentExam.Mark</td>

                }
                }
            </tr>
        </tbody>
    </table>
</div>

@code {
    private List<StudentExam> StudentExams = new List<StudentExam>();
    private Exam ExamDummy = new Exam();
    private List<Exam> Exams = new List<Exam>();

    protected override async Task OnInitializedAsync()
    {
        Guid UserId = await Http.GetFromJsonAsync<Guid>("/api/ValuesController");

        try
        {

            StudentExams = await Http.GetFromJsonAsync<List<StudentExam>>("/api/StudentExams");
            Exams = await Http.GetFromJsonAsync<List<Exam>>("/api/Exams");
            foreach (var ex in StudentExams)
            {
                if (ex.StudentId != UserId)
                {
                    StudentExams.Remove(ex);
                }
            }

        }
        catch (AccessTokenNotAvailableException exception)
        {
            exception.Redirect();
        }
        catch (Exception e)
        {

        }

    }
}
